### ISSUE TITLE
[Request] Add instructions for how to build this

### ISSUE THREAD

**Issue by captbaritone** [jberg/milkdrop-eel-parser#1]
I was interested in playing around with this project, but I'm not very familiar with Clojure. Any hints or instructions to get this building would be appreciated.

**Comment by jberg** [comment]
Oh yea, instructions would be good :D

Thanks, I'll get them out in the next few days

**Comment by jberg** [comment]
OK, I've uploaded a README with how to build and use this library. Its a bit hard to use on its own and too tied into the other libraries I use for preset conversion, and what I expect the input to look like.

Let me know how it goes!
